language: python
services:
  - docker
install:
  - docker pull peterevans/liche:1.1.1
jobs:
  include:
    # check all links in changed files using blc
    - script: bash blc-on-changed-files.sh
    - stage: cron
      if: type = cron
      # check all links using blc
      script: bash blc-good-enough.sh 10
