# Lychee configuration file
# See https://lychee.cli.rs/guides/config/
exclude_all_private = true
include_mail = false
no_progress = true
verbose = "info"
root_dir = "./"
#preprocess = { command = "./preprocess-lychee.sh" }
scheme = ["https", "http"]
