name: Link Checker
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'  
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          # note: args has a long default value; when you override it, make sure you don't accidentally forget to include the default options you want! see https://github.com/lycheeverse/lychee-action/blob/master/action.yml
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst' --accept '100..=103,200..=299, 429'
        env:
          # This token is included to avoid github.com requests to error out with status 429 (too many requests). It only works for GitHub requests (also other GitHub REST API calls), not for the rest of the web.
          GITHUB_TOKEN: ${{secrets.TOKEN_GITHUB}}
      - name: Count broken links
        run: |
            broken_max=10
            broken_count=$(printf "%d" $(grep "🚫 Errors" lychee/out.md | cut -d'|' -f3))
            if [ "$broken_count" -gt "$broken_max" ]; then
                echo "Number of broken links (${broken_count}) exceeds maximum allowed number (${broken_max})."
                cat lychee/out.md
                exit 1
            else
                echo "Number of broken links (${broken_count}) less than or equal to maximum allowed number (${broken_max})."
                exit 0
            fi
