name: Link Checker
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'  
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          # note: args has a long default value; when you override it, make sure you don't accidentally forget to include the default options you want! see https://github.com/lycheeverse/lychee-action/blob/master/action.yml
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst' --accept '100..=103,200..=299, 429' --exclude nlesc.sharepoint.com --exclude support.posit.co
        env:
          # This token is included to avoid github.com requests to error out with status 429 (too many requests). It only works for GitHub requests (also other GitHub REST API calls), not for the rest of the web.
          GITHUB_TOKEN: ${{secrets.TOKEN_GITHUB}}
