# Generates a PDF for the full guide and uploads it to Zenodo
## This action triggers when there is a new release of the guide
## Manual release of this action also triggers upload to the Zenodo Sandbox
name: Generate PDF and upload to Zenodo
on:
  # Trigger manually via the Actions tab
  workflow_dispatch:
  # Trigger when you publish a release via GitHub's release page
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the contents of your repository
        uses: actions/checkout@v4

      - name: Change absolute paths to relative
        run: perl -pi -e 's@\]\(\/@\]\(@' _sidebar.md

      - name: Pull Docker image
        run: docker pull ghcr.io/kernoeb/docker-docsify-pdf:main

      - name: Generate PDF using the Docker image
        run: |
          docker run --rm --privileged \
            -v "${{ github.workspace }}/":/home/node/docs:rw \
            -v "${{ github.workspace }}/":/home/node/pdf:rw \
            -v "${{ github.workspace }}/images/pdf-cover.pdf":/home/node/resources/cover.pdf:rw \
            --user $(id -u):$(id -g) \
            -e "PDF_OUTPUT_NAME=guide-nlesc.pdf" \
            -e "NO_SANDBOX=true" \
            ghcr.io/kernoeb/docker-docsify-pdf:main

      - name: Generate .zenodo.json from CITATION.cff
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--format zenodo --outfile .zenodo.json"

      - name: Create a draft snapshot on Zenodo Sandbox
        if: github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        uses: zenodraft/action@0.13.3
        with:
          concept:
            277496 # doesn't matter which it is, it is only for testing
            # N.B.: the actual Sandbox concept ID of the guide is 277498!
            # The -1 is a workaround for https://github.com/zenodraft/action/issues/30
          publish: false
          sandbox: true
          filenames: guide-nlesc.pdf
          metadata: .zenodo.json

      - name: Create a new snapshot in the Zenodo record
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
        uses: zenodraft/action@0.13.3
        with:
          # N.B.: the actual concept ID of the guide is 4020622!
          # The -1 is a workaround for https://github.com/zenodraft/action/issues/30
          concept: 4020621
          publish: false # let the user press the publish button manually
          sandbox: false
          filenames: guide-nlesc.pdf
          metadata: .zenodo.json
